// Switch HD-rumble decode: the stateful AM/FM codec the Switch puts on the
// wire (port of reference/switch_rumble_decoder.*). Each 4-byte side packs
// 1..3 samples; each sample carries a low and a high band, given as absolute
// values or differential deltas over per-side state:
//   low band  centered 160 Hz (range ~40..640 Hz)
//   high band centered 320 Hz (range ~80..1280 Hz)
//   amplitude 0..1 linear (2^lin, lin in [-8,0]; <= -7.9375 -> off)
// Decoded amplitude is exposed on a 0..MAX_AMP linear scale.
#pragma once
#include <cstddef>
#include <cstdint>

namespace rumble {

constexpr uint16_t MAX_AMP = 1003; // full-scale linear amplitude in Decoded

struct Decoded {
    uint16_t hf_hz = 0;   // high-band frequency, Hz (0 = off)
    uint16_t lf_hz = 0;   // low-band frequency, Hz
    uint16_t hf_amp = 0;  // 0..MAX_AMP, high-band amplitude (linear)
    uint16_t lf_amp = 0;  // 0..MAX_AMP, low-band amplitude (linear)
};

// Stateful per-controller-side decoder. The codec is differential, so one
// instance must persist per side and be fed each 4-byte side in arrival order
// (left = data[0..3], right = data[4..7]).
class SideDecoder {
public:
    SideDecoder() { reset(); }
    void reset();                          // back to silent/centered defaults
    Decoded decode(const uint8_t d[4]);    // returns the latest sample
private:
    Decoded current() const;
    void apply5(uint8_t code, bool high);  // 5-bit am+fm command on one band
    float la_, lf_, ha_, hf_;              // linear amp/freq, low & high bands
};

// Convenience: decode one 4-byte side from a fresh (default) decoder. Only
// meaningful for absolute packets; stateful streams must use SideDecoder/State.
Decoded decode_side(const uint8_t d[4]);

// amp 0..MAX_AMP -> 0x83 gain_db (~20*log10(amp/MAX_AMP)), clamped to -40;
// -128 ("off") for amp 0.
int8_t amp_to_db(uint16_t amp);

// ---- output: HD rumble as four independent 0x83 tones ----
//
// 0x83 MsgHapticLfoTone is a per-actuator (frequency, gain) tone generator,
// matching the codec's per-band (frequency, amplitude). Each decoded channel
// drives one actuator's own 0x83 stream (grips take frequency via 0x83, not
// just the pads):
//
//   left  low band  -> left  GRIP (side 3)    right low band  -> right GRIP (side 4)
//   left  high band -> left  PAD  (side 0)    right high band -> right PAD  (side 1)
//
// gain comes from the band amplitude plus a per-band trim (GRIP_GAIN_DB for the
// low band on the grips, PAD_GAIN_DB for the high band on the pads).
// side 5 (both grips at once) is avoided -- same-frequency beating.

constexpr uint8_t N_TONE = 4; // four actuators driven independently

// Actuator order (index into State::tone()); ACT_SIDE maps to the 0x83 `side`.
enum Actuator : uint8_t { ACT_L_GRIP = 0, ACT_R_GRIP = 1, ACT_L_PAD = 2, ACT_R_PAD = 3 };

constexpr size_t TONE_LEN = 10; // 0x83 report incl. id

// 0x83 tone duration; just has to outlive the 40 ms resend cadence. On release
// the consumer sends an explicit stop (see to_tone / TonePacket), so decay no
// longer waits out this duration -- it can be generous without a sluggish tail.
constexpr uint16_t TONE_DURATION_MS = 100;

// Tuning. The output gain of one tone is:
//   amp_to_db(amp)  (<= 0, the band's own loudness)
// + *_GAIN_DB       (global loudness trim, per band)
// + corr_db(...)    (frequency-response EQ, below)
// The SC's actuators and the Pro's have different frequency response curves, so
// a single scalar trim can't match them -- it's flat, the curves aren't. The
// per-band correction table is the *shape* (the Pro's resonance imprinted on the
// flatter SC actuator); the scalar *_GAIN_DB is the leftover overall loudness.
// Recalibrate the curves with tools/resonance/{sweep,pro_sweep,wav_fit}.py.
constexpr int8_t GRIP_GAIN_DB = -8;      // low band -> grips loudness trim (TUNE on hw)
constexpr int8_t PAD_GAIN_DB = 4;        // high band -> pads loudness trim (TUNE on hw)
constexpr int8_t GAIN_MAX_DB = 6;        // clip ceiling (SDL allows positive)
constexpr int8_t GAIN_MIN_DB = -40;      // inaudible floor
constexpr uint16_t FREQ_MIN_HZ = 40;     // codec low-band floor
constexpr uint16_t FREQ_MAX_HZ = 1280;   // codec high-band ceiling

// Frequency-response correction: dB to add at a given tone frequency so the SC
// actuator's output matches the real Pro's. Points are interpolated in
// log-frequency and held flat past the ends. Zero-mean by construction (overall
// level lives in *_GAIN_DB). Generated by tools/resonance/wav_fit.py from a
// paired SC+Pro sweep recording; re-run it to regenerate.
struct CorrPoint { uint16_t hz; float db; };

// grips / low band -- measured (one take; sc_grip-l vs switch_low, "box" jig).
// 83/93/105 Hz hand-corrected from feel: the as-measured curve had a -26 dB
// single-take notch at 73 Hz; median-smoothing it lifted 83-105 and flattened
// the low-end rolloff, so 90 Hz played as loud as 120 when the Pro rolls off
// below ~110. Restored a monotonic rolloff there (90 now ~-5 dB vs 120 ~0).
// A proper fix is a multi-take grip recording to kill the 73 Hz notch cleanly.
constexpr CorrPoint GRIP_CORR[] = {
    {  40,  -7.8f}, {  45, -12.0f}, {  51, -12.0f}, {  58, -10.2f},
    {  65,  -8.0f}, {  73,  -7.3f}, {  83,  -7.0f}, {  93,  -4.0f},
    { 105,   1.0f}, { 119,   0.1f}, { 134,   1.5f}, { 152,   8.4f},
    { 171,  12.0f}, { 193,  12.0f}, { 218,  11.0f}, { 246,   5.9f},
    { 278,   1.9f}, { 314,   1.9f}, { 354,   3.6f}, { 400,   4.5f},
};
constexpr size_t GRIP_CORR_N = sizeof(GRIP_CORR) / sizeof(GRIP_CORR[0]);

// pads / high band -- measured (one take; sc_pad-l vs switch_high, "box" jig),
// with the cut limited to -5 dB (wav_fit.py --cut-clamp 5). The SC pad is a
// midrange actuator: clean+strong ~150-300 Hz, then rolls off, and above ~700 Hz
// it distorts (2nd harmonic ~= fundamental, THD guard caps 709/800 at 0). The
// raw match wanted a -12 dB cut across 240-300 Hz -- but that's the content
// MEDIAN (~247 Hz, per captures/), so carving it there gutted the pads (needed
// +11 dB trim to feel them). Bounding the cut keeps the pads present where they
// matter; the top end is still honestly weaker than a Pro (no EQ fixes that).
constexpr CorrPoint PAD_CORR[] = {
    {  80,  -1.8f}, {  90,  -2.3f}, { 102,  -2.4f}, { 115,  -3.1f},
    { 130,  -4.8f}, { 147,  -5.0f}, { 166,  -5.0f}, { 187,  -5.0f},
    { 211,  -5.0f}, { 238,  -5.0f}, { 269,  -5.0f}, { 303,  -5.0f},
    { 343,   1.5f}, { 387,   7.5f}, { 436,   8.0f}, { 493,   8.0f},
    { 556,   8.0f}, { 628,   7.9f}, { 709,   0.0f}, { 800,   0.0f},
};
constexpr size_t PAD_CORR_N = sizeof(PAD_CORR) / sizeof(PAD_CORR[0]);

// dB correction at `hz` by log-frequency interpolation; 0 if the table is empty.
float corr_db(const CorrPoint* tbl, size_t n, uint16_t hz);

struct TonePacket {
    uint8_t bytes[TONE_LEN] = {0x83, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    bool active = false; // false: bytes hold a stop (gain floor); send once on
                         // the active->inactive edge, then stop refreshing.
};

// Build one actuator's 0x83 tone from a band's (freq, amp). side = 0x83 `side`
// selector; trim_db is the global loudness trim (GRIP_GAIN_DB/PAD_GAIN_DB), and
// (corr, corr_n) is the optional frequency-response table added on top (none ->
// flat). amp 0 or freq 0 -> inactive (no tone).
TonePacket to_tone(uint8_t side, uint16_t freq_hz, uint16_t amp, int8_t trim_db,
                   const CorrPoint* corr = nullptr, size_t corr_n = 0);

// Decodes a full 8-byte Switch rumble payload and tracks the four output tones.
class State {
public:
    // Returns true if any output tone changed.
    bool update(const uint8_t data[8]);
    const TonePacket& tone(int actuator) const { return tones_[actuator & 3]; }
    bool active() const {
        return tones_[0].active || tones_[1].active ||
               tones_[2].active || tones_[3].active;
    }
    const Decoded& left() const { return l_; }
    const Decoded& right() const { return r_; }

private:
    SideDecoder ldec_, rdec_;
    Decoded l_, r_;
    TonePacket tones_[N_TONE];
};

} // namespace rumble
